project:
  type: website
  output-dir: docs

website:
  favicon: images/logo.png
  navbar:
    logo: images/logo.png
    left: 
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: resume.qmd
        text: Resume
      - href: blogs.qmd
        text: My Blog
    
    right: 
      - icon: linkedin
        href: https://www.linkedin.com/in/raymond-hunter-90a8081a7/
      - icon: github
        href: https://github.com/ramhunte
      - icon: envelope
        href: mailto:rmhunter999@gmail.com  
 
 
  page-footer: 
    left: 
      - "Copyright 2024, Raymond Hunter"
    right: 
      - "Made using Quarto"

  
    
    


format:
  html:
    theme: 
    - styles.scss
    mainfont: Raleway
    toc: false
    anchor-sections: false
    # page-layout: full

editor: visual

execute: 
  freeze: auto

